// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadelSimple.Models.Data;

#nullable disable

namespace PadelSimple.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819213650_VertalingNederlands")]
    partial class VertalingNederlands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Materiaal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalInInventaris")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeschikbaarAantal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Huurprijs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerwijderd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerwijderdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materialen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AantalInInventaris = 20,
                            BeschikbaarAantal = 0,
                            Huurprijs = 5.00m,
                            IsActief = true,
                            IsVerwijderd = false,
                            Naam = "Padelracket"
                        },
                        new
                        {
                            Id = 2,
                            AantalInInventaris = 30,
                            BeschikbaarAantal = 0,
                            Huurprijs = 2.50m,
                            IsActief = true,
                            IsVerwijderd = false,
                            Naam = "Set Ballen"
                        },
                        new
                        {
                            Id = 3,
                            AantalInInventaris = 15,
                            BeschikbaarAantal = 0,
                            Huurprijs = 1.50m,
                            IsActief = true,
                            IsVerwijderd = false,
                            Naam = "Beschermingsbril"
                        });
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Reservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalMateriaal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalSpelers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EindUur")
                        .HasColumnType("TEXT");

                    b.Property<string>("GebruikerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerwijderd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MateriaalId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartUur")
                        .HasColumnType("TEXT");

                    b.Property<int>("TerreinId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalePrijs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("VerwijderdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GebruikerId");

                    b.HasIndex("MateriaalId");

                    b.HasIndex("TerreinId");

                    b.ToTable("Reservaties");
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.ReservatieMateriaal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aantal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MateriaalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservatieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MateriaalId");

                    b.HasIndex("ReservatieId");

                    b.ToTable("ReservatieMaterialen");
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Terrein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capaciteit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndoors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerwijderd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Uurtarief")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("VerwijderdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Terreinen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capaciteit = 4,
                            IsIndoors = true,
                            IsVerwijderd = false,
                            Naam = "Terrein 1 (Overdekt)",
                            Uurtarief = 18.00m
                        },
                        new
                        {
                            Id = 2,
                            Capaciteit = 4,
                            IsIndoors = false,
                            IsVerwijderd = false,
                            Naam = "Terrein 2 (Buiten)",
                            Uurtarief = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            Capaciteit = 4,
                            IsIndoors = true,
                            IsVerwijderd = false,
                            Naam = "Terrein 3 (Overdekt VIP)",
                            Uurtarief = 25.00m
                        });
                });

            modelBuilder.Entity("PadelSimple.Models.Identity.AppGebruiker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGeblokkeerd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerwijderd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerwijderdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PadelSimple.Models.Identity.AppRol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ROLE_ADMIN",
                            ConcurrencyStamp = "a1b2c3d4-0000-0000-0000-000000000001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ROLE_MEDEWERKER",
                            ConcurrencyStamp = "a1b2c3d4-0000-0000-0000-000000000003",
                            Name = "Medewerker",
                            NormalizedName = "MEDEWERKER"
                        },
                        new
                        {
                            Id = "ROLE_KLANT",
                            ConcurrencyStamp = "a1b2c3d4-0000-0000-0000-000000000002",
                            Name = "Klant",
                            NormalizedName = "KLANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PadelSimple.Models.Identity.AppRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PadelSimple.Models.Identity.AppGebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PadelSimple.Models.Identity.AppGebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("PadelSimple.Models.Identity.AppRol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelSimple.Models.Identity.AppGebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PadelSimple.Models.Identity.AppGebruiker", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Reservatie", b =>
                {
                    b.HasOne("PadelSimple.Models.Identity.AppGebruiker", "Gebruiker")
                        .WithMany("Reservaties")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PadelSimple.Models.Domain.Materiaal", "Materiaal")
                        .WithMany("Reservaties")
                        .HasForeignKey("MateriaalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PadelSimple.Models.Domain.Terrein", "Terrein")
                        .WithMany("Reservaties")
                        .HasForeignKey("TerreinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gebruiker");

                    b.Navigation("Materiaal");

                    b.Navigation("Terrein");
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.ReservatieMateriaal", b =>
                {
                    b.HasOne("PadelSimple.Models.Domain.Materiaal", "Materiaal")
                        .WithMany()
                        .HasForeignKey("MateriaalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PadelSimple.Models.Domain.Reservatie", "Reservatie")
                        .WithMany("ReservatieMaterialen")
                        .HasForeignKey("ReservatieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materiaal");

                    b.Navigation("Reservatie");
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Materiaal", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Reservatie", b =>
                {
                    b.Navigation("ReservatieMaterialen");
                });

            modelBuilder.Entity("PadelSimple.Models.Domain.Terrein", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("PadelSimple.Models.Identity.AppGebruiker", b =>
                {
                    b.Navigation("Reservaties");
                });
#pragma warning restore 612, 618
        }
    }
}
